{{- $settings := .Values.settings | default dict -}}
{{- if and (eq (include "seerr.settings.helmEnabled" .) "true") (not $settings.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seerr.settings.secretName" . }}
  labels:
    {{- include "seerr.labels" . | nindent 4 }}
type: Opaque
stringData:
  settings.json: |
    {{- include "seerr.settings.json" . | nindent 4 }}
{{- end }}
